### ISSUE TITLE
Ability to ignore nicks

### ISSUE THREAD

**Issue by polyzen** [nuxeh/url-bot-rs#20]
For example other bots in the room.

**Comment by nuxeh** [comment]
Yep, good idea.

Specify --ignore-nick multiple times, or also specify in the config?

Could then put the all ignored nicks in a hashset, and skip processing on their messages.

**Comment by polyzen** [comment]
Is url-bot expected to work with PM's? Prior to the limits PR, the bot could be crashed via PM, but it doesn't respond for valid requests. Perhaps ignoring PM's can be implemented along with this.

**Comment by fleaz** [comment]
Hey, 
are  there any updates on this?
Because we e.g. have multiple rooms where we use a [CptHook](https://github.com/fleaz/CptHook) bot to get push/merge/build events from Gitlab which contain a link to the repo that gets parsed by url-bot-rs.

Also some of the repos  are not public and then the bot only prints a "Sign in - Gitlab" because it was redirected.

**Comment by nuxeh** [comment]
For what it's worth, the solution i've seen commonly for this is to have bots post as notice rather than message, which are usually not picked up by other bots. `url-bot-rs` is configurable to post notices for this reason, but it would depend on your other bots also supporting a similar feature.

But anyway, nick ignores would be a very easy change to implement, and since it's clear there's demand for it I'll do this shortly unless someone else fancies it.

**Comment by fleaz** [comment]
That was fast, thanks!

But yes, just learned about the benefits of notices and I'm currently implementing this feature in CptHook :D
