### ISSUE TITLE
Install on WSL

### ISSUE THREAD

**Issue by furx** [nuxeh/url-bot-rs#238]
I'm trying to install url-bot-rs on Windows Subsystem for Linux running debian.

So far I was able to execute the ```cargo install cargo-deb``` command, but ```cargo deb --install``` throws an error:

```
root@HomeServer:~/url-bot-rs# cargo deb --install
    Finished release [optimized] target(s) in 0.26s
/root/url-bot-rs/target/debian/url-bot-rs_0.2.2_amd64.deb
(Reading database ... 26710 files and directories currently installed.)
Preparing to unpack .../url-bot-rs_0.2.2_amd64.deb ...
Removed /etc/systemd/system/multi-user.target.wants/url-bot-rs.service.
Failed to stop url-bot-rs.service: Launch helper exited with unknown return code 1
See system logs and 'systemctl status url-bot-rs.service' for details.
Failed to get load state of url-bot-rs.service: Launch helper exited with unknown return code 1
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
dpkg: ... it looks like that went OK
Unpacking url-bot-rs (0.2.2) over (0.2.2) ...
Setting up url-bot-rs (0.2.2) ...
useradd: user 'url-bot-rs' already exists
Created symlink /etc/systemd/system/multi-user.target.wants/url-bot-rs.service → /etc/systemd/system/url-bot-rs.service.
Failed to start url-bot-rs.service: Launch helper exited with unknown return code 1
See system logs and 'systemctl status url-bot-rs.service' for details.
dpkg: error processing package url-bot-rs (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 url-bot-rs
cargo-deb: installation failed, because dpkg -i returned error
```

```
root@HomeServer:~/url-bot-rs# systemctl status url-bot-rs.service
Failed to get properties: Launch helper exited with unknown return code 1
```

WSL does not support systemd, how can I solve this?

**Comment by nuxeh** [comment]
Hi!

Sorry for the delay, only just seen this issue.

One thing that might get you off the ground is that from v0.2.3 (just pushed to [crates.io](https://crates.io/crates/url-bot-rs)), `url-bot-rs` has reconnection, which can be set in the configuration file. As such it will try to persistently connect to networks, even if IRC errors occur.

Otherwise, as to running systemd in WSL, a quick search came up with [this](https://github.com/arkane-systems/genie), not sure if that would be any use.

A bodge solution would be to run it in a `while true; do` bash loop.

WSL isn't a target I had considered until now, so if a good solution for this is found, it would be good to add it to the documentation.

**Comment by nuxeh** [comment]
...so with reconnection, you wouldn't need the deb package install, and could just `cargo install --path .` or `cargo install url-bot-rs` and run `url-bot-rs` manually.

It seems like a tricky thing to run services in WSL.

**Comment by nuxeh** [comment]
Hi @furx, did you get anywhere with this, or still interested in getting url-bot running?
