### ISSUE TITLE
Add service file systemd, update README (autostart)

### ISSUE THREAD

**Issue by mandala-mbwa** [nuxeh/url-bot-rs#54]
Create new service

`sudo systemctl edit --force url-bot-rs.service`

Edit service file (file url-bot-rs.service)

```
[Unit]
Description=url-bot-rs
After=network.target
Requires=network.target

[Service]
User=user
WorkingDirectory=/home/user/.cargo/bin/
ExecStart=/home/user/.cargo/bin/url-bot --conf=/home/user/url-bot-rs/config.toml
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```
Enable new service

`sudo systemctl enable url-bot-rs.service`

Start service

`sudo systemctl start url-bot-rs.service`

Status service (success check)

`sudo systemctl status url-bot-rs.service`

**Comment by nuxeh** [comment]
Yes, good idea, thanks :)

This reminds me, we need standard paths to place the config and database, which would help standardise the paths here (see #19). At some point it would be good to commit this into the codebase, perhaps the example systemd unit as a file, and README update.

Since you included `SuccessExitStatus=143`, i guess this means SIGKILL isn't being handled properly? I wonder if that's something that's worth doing, and actually how easy it would be to gracefully shut down the asynchronous stuff in the `irc` crate.

**Comment by mandala-mbwa** [comment]
`SuccessExitStatus=143` no need, everything is fine without it, I just forgot to delete.

**Comment by mandala-mbwa** [comment]
nobody

old way

for those who understand.

**Comment by polyzen** [comment]
That may work, not sure.
